name: ecommerce_int2
description: It is about a complete ecommerce app for Android and iOS.

version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Paquetes principales utilizados en el proyecto
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  chewie: ^1.8.5
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  cupertino_icons: ^1.0.5
  card_swiper: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  rubber: ^1.0.1
  pin_code_text_field: ^1.8.0
  http: ^1.2.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.1
  numberpicker: ^2.1.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/shopeLogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
