// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgzpuyJHqhbU8f202JTd156sMYCAP5U8I',
    appId: '1:534888827224:web:dae0e124845f498549fd2d',
    messagingSenderId: '534888827224',
    projectId: 'flutterecommercetemplate-72969',
    authDomain: 'flutterecommercetemplate-72969.firebaseapp.com',
    storageBucket: 'flutterecommercetemplate-72969.appspot.com',
    measurementId: 'G-PX6ZBPVVL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf6uSCKRK3SlONgN4cJRZGwllJnaItEvg',
    appId: '1:534888827224:android:59b43536a18238d649fd2d',
    messagingSenderId: '534888827224',
    projectId: 'flutterecommercetemplate-72969',
    storageBucket: 'flutterecommercetemplate-72969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZzzYJ7ECt0V16s4goeCShKd4ro5YQtvE',
    appId: '1:534888827224:ios:44c4c27de0cec0d849fd2d',
    messagingSenderId: '534888827224',
    projectId: 'flutterecommercetemplate-72969',
    storageBucket: 'flutterecommercetemplate-72969.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZzzYJ7ECt0V16s4goeCShKd4ro5YQtvE',
    appId: '1:534888827224:ios:4507e8476a62851149fd2d',
    messagingSenderId: '534888827224',
    projectId: 'flutterecommercetemplate-72969',
    storageBucket: 'flutterecommercetemplate-72969.appspot.com',
    iosBundleId: 'com.int2.flutterEcommerceTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgzpuyJHqhbU8f202JTd156sMYCAP5U8I',
    appId: '1:534888827224:web:e9b43e08a75c156e49fd2d',
    messagingSenderId: '534888827224',
    projectId: 'flutterecommercetemplate-72969',
    authDomain: 'flutterecommercetemplate-72969.firebaseapp.com',
    storageBucket: 'flutterecommercetemplate-72969.appspot.com',
    measurementId: 'G-HZRCPB7ZQT',
  );

}